include: [".well-known"]
exclude:
  - _markup
  - src
  - .editorconfig
  - .env.dist
  - .gitignore
  - docker-compose.yaml
  - bower.json
  - gulpfile.json
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
  - TODO
